//
//  Mathematician.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/11.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import MapKit

class Mathematician: Actor {
    
    private func _beCalculateRange(coordinate: CLLocationCoordinate2D, range: Float64) {
//        let aaa = calculateRange(coordinate: coordinate, range: range)
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Mathematician {

    @discardableResult
    public func beCalculateRange(coordinate: CLLocationCoordinate2D, range: Float64) -> Self {
        unsafeSend { self._beCalculateRange(coordinate: coordinate, range: range) }
        return self
    }

}
