//
//  Mathematician.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/11.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import MapKit

class Mathematician: Actor {
    
    private func _beCalculateRange(_ sender: Actor,
                                   _ coordinate: CLLocationCoordinate2D,
                                   _ range: Float64,
                                   _ complete: @escaping (GQSearchRange) -> Void) {
        sender.unsafeSend {
            complete(
                Haversin().calculateRange(
                    coordinate: coordinate, range: range))
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Mathematician {

    @discardableResult
    public func beCalculateRange(_ sender: Actor, _ coordinate: CLLocationCoordinate2D, _ range: Float64, _ complete: @escaping (GQSearchRange) -> Void) -> Self {
        unsafeSend { self._beCalculateRange(sender, coordinate, range, complete) }
        return self
    }

}
