//
//  GeoCoder.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/13.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import MapKit

class GeoCoder: Actor {
    private func _beCodeAddress(
        _ sender: Actor,_ address: String,
        _ complete: @escaping ([CLPlacemark]?, Error?) -> Void) {
        let geoCoder = CLGeocoder()
        geoCoder.geocodeAddressString(address) { (placemarks, error) in
            sender.unsafeSend {
                complete(placemarks, error)
            }
        }
    }
    private func _beReverseLocation(
        _ sender: Actor,location: CLLocation,
        _ complete: @escaping ([CLPlacemark]?, Error?) -> Void) {
        let geoCoder = CLGeocoder()
        geoCoder.reverseGeocodeLocation(location) { (placemarks, error) in
            sender.unsafeSend {
                complete(placemarks, error)
            }
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension GeoCoder {

    @discardableResult
    public func beCodeAddress(_ sender: Actor, _ address: String, _ complete: @escaping ([CLPlacemark]?, Error?) -> Void) -> Self {
        unsafeSend { self._beCodeAddress(sender, address, complete) }
        return self
    }
    @discardableResult
    public func beReverseLocation(_ sender: Actor, location: CLLocation, _ complete: @escaping ([CLPlacemark]?, Error?) -> Void) -> Self {
        unsafeSend { self._beReverseLocation(sender, location: location, complete) }
        return self
    }

}
