//
//  MapNavigator.swift
//  WhatToEat
//
//  Created by YuCheng on 2020/9/18.
//  Copyright © 2020 YuCheng. All rights reserved.
//

import UIKit
import MapKit
import Flynn

extension MKMapView {
    //缩放级别
    var zoomLevel: Int {
        //获取缩放级别
        get {
//            return log2(360 * Double(frame.size.width) / 256.0 / region.span.longitudeDelta)
            return Int(log2(360 * (Double(self.frame.size.width/256)/self.region.span.longitudeDelta)) + 1)
        }
        //设置缩放级别
        set (newZoomLevel){
            setCenterCoordinate(coordinate: self.centerCoordinate, zoomLevel: newZoomLevel,
                                animated: false)
        }
    }
    
    //设置缩放级别时调用
    private func setCenterCoordinate(coordinate: CLLocationCoordinate2D, zoomLevel: Int,
                                     animated: Bool){
        let span = MKCoordinateSpan(latitudeDelta: 0,
                                    longitudeDelta: 360 / pow(2, Double(zoomLevel)) * Double(self.frame.size.width) / 256)
        setRegion(MKCoordinateRegion(center: centerCoordinate, span: span), animated: animated)
    }
}

class MapNavigator: Actor {

    private let mkMapView: MKMapView
    
    init(mapView: MKMapView) {
        mkMapView = mapView
    }
    
    private func _beSetCenterCoordinate(coordinate: CLLocationCoordinate2D) {
        DispatchQueue.main.async { [self] in
            mkMapView.centerCoordinate = coordinate
        }
    }
    private func _beAddCircleOverlay(radius: CLLocationDistance) {
        // Radius is measured in meters
        DispatchQueue.main.async { [self] in
            if mkMapView.overlays.count > 0 {
                mkMapView.removeOverlays(mkMapView.overlays)
            }
            let circle = MKCircle(center: mkMapView.camera.centerCoordinate,
                                  radius: radius)
            mkMapView.addOverlay(circle)
        }
    }
    
    
    private func _beSetRegion(
        _ center: CLLocationCoordinate2D,
        _ distance: Float64) {
        let region = MKCoordinateRegion(
            center: center,
            latitudinalMeters: CLLocationDistance(distance),
            longitudinalMeters: CLLocationDistance(distance)
        )
        DispatchQueue.main.async { [self] in
            mkMapView.setRegion(region, animated: true)
        }
    }
    private func _beRemoveAnnotations(
        sender: Actor,
        _ annotations: [MKAnnotation],_ complete: @escaping () -> Void) {
        DispatchQueue.main.async { [self] in
            mkMapView.removeAnnotations(annotations)
            sender.unsafeSend {
                complete()
            }
        }
    }
    private func _beShowAnnotations(
        annotations: [MKPointAnnotation], animated: Bool) {
        DispatchQueue.main.async { [self] in
            mkMapView.showAnnotations(annotations, animated: animated)
        }
    }
    private func _beGetZoomLevel(sender: Actor,complete: @escaping (Int) -> Void) {
        DispatchQueue.main.async { [self] in
            let zoomLevel = mkMapView.zoomLevel
            sender.unsafeSend {
                complete(zoomLevel)
            }
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension MapNavigator {

    @discardableResult
    public func beSetCenterCoordinate(coordinate: CLLocationCoordinate2D) -> Self {
        unsafeSend { self._beSetCenterCoordinate(coordinate: coordinate) }
        return self
    }
    @discardableResult
    public func beAddCircleOverlay(radius: CLLocationDistance) -> Self {
        unsafeSend { self._beAddCircleOverlay(radius: radius) }
        return self
    }
    @discardableResult
    public func beSetRegion(_ center: CLLocationCoordinate2D, _ distance: Float64) -> Self {
        unsafeSend { self._beSetRegion(center, distance) }
        return self
    }
    @discardableResult
    public func beRemoveAnnotations(sender: Actor, _ annotations: [MKAnnotation], _ complete: @escaping () -> Void) -> Self {
        unsafeSend { self._beRemoveAnnotations(sender: sender, annotations, complete) }
        return self
    }
    @discardableResult
    public func beShowAnnotations(annotations: [MKPointAnnotation], animated: Bool) -> Self {
        unsafeSend { self._beShowAnnotations(annotations: annotations, animated: animated) }
        return self
    }
    @discardableResult
    public func beGetZoomLevel(sender: Actor, complete: @escaping (Int) -> Void) -> Self {
        unsafeSend { self._beGetZoomLevel(sender: sender, complete: complete) }
        return self
    }

}
