//
//  ToolMan.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/3/3.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import UIKit
import Flynn

class ToolMan: Actor {
    private func _beResizeImage(
        sender: Actor,image: UIImage, width: CGFloat,
        _ complete: @escaping (UIImage) -> Void) {
        let size = CGSize(width: width, height:
                            image.size.height * width / image.size.width)
        let renderer = UIGraphicsImageRenderer(size: size)
        let newImage = renderer.image { (context) in
            image.draw(in: renderer.format.bounds)
        }
        sender.unsafeSend {
            complete(newImage)
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension ToolMan {

    @discardableResult
    public func beResizeImage(sender: Actor, image: UIImage, width: CGFloat, _ complete: @escaping (UIImage) -> Void) -> Self {
        unsafeSend { self._beResizeImage(sender: sender, image: image, width: width, complete) }
        return self
    }

}
