//
//  Courier.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/11.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn

struct Parcel {
    var parcelType: String = ""
    var sender = ""
    var content: Any
}

class Courier: Actor {
    private var courierBag: [String: Any] = [:]
    
    private func _bePackageParcel(sender: Actor, recipient: String,
                               content: Any) {
        var parcel = Parcel(content: content)
        parcel.sender = String(describing: type(of: sender))
        var parcelSet: NSMutableSet
        if courierBag[recipient] == nil {
            parcelSet = NSMutableSet()
        } else {
            parcelSet = courierBag[recipient] as! NSMutableSet
        }
        if !parcelSet.contains(parcel) {
            parcelSet.add(parcel)
            courierBag[recipient] = parcelSet
        }
    }
    
    
    private func _beCollect(_ recipient: Actor,
                            _ complete: @escaping (NSSet?) -> Void) {
        let key = String(describing: type(of: recipient))
        let parcelSet = NSSet.init(set: (courierBag[key] as! NSMutableSet))
        courierBag.removeValue(forKey: key)
        recipient.unsafeSend {
            complete(parcelSet)
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Courier {

    @discardableResult
    public func bePackageParcel(sender: Actor, recipient: String, content: Any) -> Self {
        unsafeSend { self._bePackageParcel(sender: sender, recipient: recipient, content: content) }
        return self
    }
    @discardableResult
    public func beCollect(_ recipient: Actor, _ complete: @escaping (NSSet?) -> Void) -> Self {
        unsafeSend { self._beCollect(recipient, complete) }
        return self
    }

}
