//
//  TimeGuardian.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/3/3.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn

class TimeGuardian: Actor {
    private func _beUTC_ISO8601Date(
        sender:Actor,dateString: String,
        _ complete: @escaping (Date) -> Void) {
        // The default timeZone on ISO8601DateFormatter is UTC.
        // Set timeZone to UTTimeZone.current to get local time.
        let localISOFormatter = ISO8601DateFormatter()
        localISOFormatter.timeZone = TimeZone.current
        let newDate = localISOFormatter.date(from: dateString) ?? Date()
        sender.unsafeSend {
            complete(newDate)
        }
    }
    private func _beUTC_ISO8601DateString(
        sender: Actor,date: Date,
        _ complete: @escaping (String) -> Void) {
        // The default timeZone for ISO8601DateFormatter is UTC
        let utcISODateFormatter = ISO8601DateFormatter()
        let utcString = utcISODateFormatter.string(from: date)
        sender.unsafeSend {
            complete(utcString)
        }
    }
    private func _beToUTCString(
        sender: Actor,
        date: Date, dateStyle: DateFormatter.Style,
        timeStyle: DateFormatter.Style,
        _ complete: @escaping (String) -> Void) {
        let utcDateFormatter = DateFormatter()
        utcDateFormatter.dateStyle = dateStyle
        utcDateFormatter.timeStyle = timeStyle
        utcDateFormatter.timeZone = TimeZone(abbreviation: "UTC")
        let newDateString = utcDateFormatter.string(from: date)
        sender.unsafeSend {
            complete(newDateString)
        }
    }
    private func _beToUTC(
        sender:Actor,formatter: String,dateToConvert:String,
        _ complete: @escaping (String) -> Void) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = formatter
        let convertedDate = dateFormatter.date(from: dateToConvert)
        dateFormatter.timeZone = TimeZone(identifier: "UTC")
        let utcString = dateFormatter.string(from: convertedDate!)
        sender.unsafeSend {
            complete(utcString)
        }
    }
    private func _beDateToString(
        sender: Actor,date:Date, dateFormat: String,
        _ complete: @escaping (String) -> Void) {
        let formatter = DateFormatter()
        formatter.dateFormat = dateFormat
        let dateString = formatter.string(from: date)
        sender.unsafeSend {
            complete(dateString)
        }
    }
    private func _beStringToDate(
        sender:Actor,
        toDate dateString: String?, formatter: String?,
        _ complete: @escaping (Date) -> Void) {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = formatter
        let newDate = dateFormatter.date(from: dateString ?? "") ?? Date()
        sender.unsafeSend {
            complete(newDate)
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension TimeGuardian {

    @discardableResult
    public func beUTC_ISO8601Date(sender: Actor, dateString: String, _ complete: @escaping (Date) -> Void) -> Self {
        unsafeSend { self._beUTC_ISO8601Date(sender: sender, dateString: dateString, complete) }
        return self
    }
    @discardableResult
    public func beUTC_ISO8601DateString(sender: Actor, date: Date, _ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beUTC_ISO8601DateString(sender: sender, date: date, complete) }
        return self
    }
    @discardableResult
    public func beToUTCString(sender: Actor, date: Date, dateStyle: DateFormatter.Style, timeStyle: DateFormatter.Style, _ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beToUTCString(sender: sender, date: date, dateStyle: dateStyle, timeStyle: timeStyle, complete) }
        return self
    }
    @discardableResult
    public func beToUTC(sender: Actor, formatter: String, dateToConvert: String, _ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beToUTC(sender: sender, formatter: formatter, dateToConvert: dateToConvert, complete) }
        return self
    }
    @discardableResult
    public func beDateToString(sender: Actor, date: Date, dateFormat: String, _ complete: @escaping (String) -> Void) -> Self {
        unsafeSend { self._beDateToString(sender: sender, date: date, dateFormat: dateFormat, complete) }
        return self
    }
    @discardableResult
    public func beStringToDate(sender: Actor, toDate dateString: String?, formatter: String?, _ complete: @escaping (Date) -> Void) -> Self {
        unsafeSend { self._beStringToDate(sender: sender, toDate: dateString, formatter: formatter, complete) }
        return self
    }

}
