//
//  DataManager.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/13.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import CoreLocation
import MapKit

class DataManager: Actor {
    private func _beParsePlaceMarktoGQInput(
        _ sender: Actor,_ placeMarks:[CLPlacemark],
        _ complete: @escaping ([GQInputObject]) -> Void) {
        var result: [GQInputObject] = []
        for placeMark in placeMarks {
            var inputObj: GQInputObject = initGQInputObject()
            inputObj.address.latitude = String(format: "%f", placeMark.location?.coordinate.latitude ?? 0.0)
            inputObj.address.longitude = String(format: "%f", placeMark.location?.coordinate.longitude ?? 0.0)
            inputObj.address.nation = placeMark.country
            inputObj.address.isoNationCode = placeMark.isoCountryCode
            inputObj.address.locality = placeMark.locality
            inputObj.address.subLocality = placeMark.subLocality
            inputObj.address.administrativeArea = placeMark.administrativeArea
            inputObj.address.subAdministrativeArea = placeMark.subAdministrativeArea
            inputObj.address.postalCode = placeMark.postalCode
            inputObj.address.thoroughfare = placeMark.thoroughfare
            inputObj.address.subThoroughfare = placeMark.subThoroughfare
            inputObj.address.completeInfo = combineAddressCompleteInfo(input: inputObj)
            result.append(inputObj)
        }
        sender.unsafeSend {
            complete(result)
        }
    }
    private func _beParsePlaceMarkToAddressDqCmd(
        _ sender: Actor,_ placeMark: CLPlacemark,
        _ complete: @escaping (AddressDqCmd) -> Void) {
        var addressDqCmd = AddressDqCmd()
        if placeMark.country != nil {
            addressDqCmd.nation = placeMark.country
        }
        if placeMark.isoCountryCode != nil {
            addressDqCmd.isoNationCode = placeMark.isoCountryCode
        }
        if placeMark.locality != nil {
            addressDqCmd.locality = placeMark.locality
        }
        if placeMark.subLocality != nil {
            addressDqCmd.subLocality = placeMark.subLocality
        }
        if placeMark.administrativeArea != nil {
            addressDqCmd.administrativeArea = placeMark.administrativeArea
        }
        if placeMark.subAdministrativeArea != nil {
            addressDqCmd.subAdministrativeArea = placeMark.subAdministrativeArea
        }
        if placeMark.postalCode != nil {
            addressDqCmd.postalCode = placeMark.postalCode
        }
        if placeMark.thoroughfare != nil {
            addressDqCmd.thoroughfare = placeMark.thoroughfare
        }
        if placeMark.subThoroughfare != nil {
            addressDqCmd.subThoroughfare = placeMark.subThoroughfare
        }
        sender.unsafeSend {
            complete(addressDqCmd)
        }
    }
    private func _beParseLocDynamicQueryDataToGQInput(
        _ sender: Actor,
        _ queryData:[LocationsDynamicQueryQuery.Data.LocationsDynamicQuery?],
        _ complete:@escaping ([GQInputObject]) -> Void) {
        if queryData.count > 0 {
            var results = [GQInputObject]()
            for data in queryData {
                let inputObj = locationsDynamicQueryToGQInputObj(result: data!)
                results.append(inputObj)
            }
            sender.unsafeSend {
                complete(results)
            }
        }
    }
    
    // MARK: - Private
    private func combineAddressCompleteInfo(input: GQInputObject) -> String {
        let mutabletext = NSMutableString(string: (input.address.administrativeArea ?? "") ?? "")
        mutabletext.append((input.address.subAdministrativeArea ?? "") ?? "")
        mutabletext.append((input.address.locality ?? "") ?? "")
        mutabletext.append((input.address.thoroughfare ?? "") ?? "")
        mutabletext.append(" ")
        mutabletext.append((input.address.subThoroughfare ?? "") ?? "")
        return mutabletext as String
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension DataManager {

    @discardableResult
    public func beParsePlaceMarktoGQInput(_ sender: Actor, _ placeMarks: [CLPlacemark], _ complete: @escaping ([GQInputObject]) -> Void) -> Self {
        unsafeSend { self._beParsePlaceMarktoGQInput(sender, placeMarks, complete) }
        return self
    }
    @discardableResult
    public func beParsePlaceMarkToAddressDqCmd(_ sender: Actor, _ placeMark: CLPlacemark, _ complete: @escaping (AddressDqCmd) -> Void) -> Self {
        unsafeSend { self._beParsePlaceMarkToAddressDqCmd(sender, placeMark, complete) }
        return self
    }
    @discardableResult
    public func beParseLocDynamicQueryDataToGQInput(_ sender: Actor, _ queryData: [LocationsDynamicQueryQuery.Data.LocationsDynamicQuery?], _ complete: @escaping ([GQInputObject]) -> Void) -> Self {
        unsafeSend { self._beParseLocDynamicQueryDataToGQInput(sender, queryData, complete) }
        return self
    }

}
