//
//  DataManager.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/13.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import CoreLocation
import MapKit

class DataManager: Actor {
    private func _beParsePlaceMarktoGQInput(
        _ sender: Actor,_ placeMarks:[CLPlacemark],
        _ complete: @escaping ([GQInputObject]) -> Void) {
        var result: [GQInputObject] = []
        for placeMark in placeMarks {
            var inputObj: GQInputObject = initGQInputObject()
            inputObj.address.latitude = String(format: "%f", placeMark.location?.coordinate.latitude ?? 0.0)
            inputObj.address.longitude = String(format: "%f", placeMark.location?.coordinate.longitude ?? 0.0)
            inputObj.address.nation = placeMark.country
            inputObj.address.isoNationCode = placeMark.isoCountryCode
            inputObj.address.locality = placeMark.locality
            inputObj.address.subLocality = placeMark.subLocality
            inputObj.address.administrativeArea = placeMark.administrativeArea
            inputObj.address.subAdministrativeArea = placeMark.subAdministrativeArea
            inputObj.address.postalCode = placeMark.postalCode
            inputObj.address.thoroughfare = placeMark.thoroughfare
            inputObj.address.subThoroughfare = placeMark.subThoroughfare
            result.append(inputObj)
        }
        sender.unsafeSend {
            complete(result)
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension DataManager {

    @discardableResult
    public func beParsePlaceMarktoGQInput(_ sender: Actor, _ placeMarks: [CLPlacemark], _ complete: @escaping ([GQInputObject]) -> Void) -> Self {
        unsafeSend { self._beParsePlaceMarktoGQInput(sender, placeMarks, complete) }
        return self
    }

}
