//
//  GourmetDetailScenario.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/22.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn

struct DetailTableData {
    var dataObj:
        LocationsDynamicQueryQuery.Data.LocationsDynamicQuery
    var dataSource: Array<TemplateProtocol> = []
    init(dataObj: LocationsDynamicQueryQuery.Data.LocationsDynamicQuery) {
        self.dataObj = dataObj
        dataSource = createDataSource()
    }
    mutating func reloadData(data: LocationsDynamicQueryQuery.Data.LocationsDynamicQuery) {
        self.dataObj = data
        dataSource = createDataSource()
    }
    private func createDataSource() -> Array<TemplateProtocol> {
        return [
            LRTemplate(leftViewItem: LabelItem(text: "Title"),
                           rightViewItem: LabelItem(text: self.dataObj.shopBranch?.shop?.title ?? "")),
            LRTemplate(leftViewItem: LabelItem(text: "Style"),
                           rightViewItem: LabelItem(text: (self.dataObj.shopBranch?.shop?.style ?? "") )),
            LRTemplate(leftViewItem: LabelItem(text: "Type"),
                           rightViewItem: LabelItem(text: (self.dataObj.shopBranch?.shop?.type ?? "") )),
            LRTemplate(leftViewItem: LabelItem(text: "Under\nPrice"),
                           rightViewItem: LabelItem(text:
                                                            String(format: "%.2f", (self.dataObj.shopBranch?.shop?.underPrice ?? 0.0)!))),
            LRTemplate(leftViewItem: LabelItem(text: "Name"),
                           rightViewItem: LabelItem(text: "")),
            LRTemplate(leftViewItem: LabelItem(text: "Tel"),
                           rightViewItem: LabelItem(text: (dataObj.shopBranch?.tel ?? "") )),
            LRTemplate(leftViewItem: LabelItem(text: "Address"),
                           rightViewItem: LabelItem(text: dataObj.completeInfo ?? "")),
            ButtonTemplate(cornerRadius: 2.0, titleText: "Navigation")
        ]
    }
}
class GourmetDetailScenario: Actor {
    private func _beCollectParcel(
        _ complete: @escaping (
            LocationsDynamicQueryQuery.Data.LocationsDynamicQuery) -> Void) {
        LogisticsCenter.shared.collectPacels(recipient: self) { (parcelSet) in
            guard parcelSet?.count ?? 0 > 0 else {
                return}
            for parcel in parcelSet! {
                let parcelItem = parcel as! Parcel
                if let content = parcelItem.content as? LocationsDynamicQueryQuery.Data.LocationsDynamicQuery {
                    complete(content)
                }
            }
        }
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension GourmetDetailScenario {

    @discardableResult
    public func beCollectParcel(_ complete: @escaping (
            LocationsDynamicQueryQuery.Data.LocationsDynamicQuery) -> Void) -> Self {
        unsafeSend { self._beCollectParcel(complete) }
        return self
    }

}
