//
//  SearchLocScenario.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/13.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import CoreLocation
import MapKit

class SearchLocScenario: Actor,PilotProtocol {
    
    enum SearchMode {
        case Map, Google
    }
    
    private let pilot = Pilot(100.0, accuracy: .ACCURACY_BEST_FOR_NAVIGATION)
    private var searchMode: SearchMode = .Map
    private var isWebViewCreated = false
    private var foundBranchId = ""
    private var locParcel = Parcel(content: "")
    
    override init() {
        super.init()
//        pilot.beRegisterSender(self)
        pilot.beRequestAuthorization(.REQUEST_AUTHORIZATION_WHENINUSE)
    }
    
    // MARK: - scenario actions
    private func _beRequestCurrentLocation() {
        pilot.beRequestCurrentLocation()
    }
    private func _beInquireIntoAddressesLocation(address: String) {
        GeoCoder().beCodeAddress(self, address) { (placemarks, error) in
            if error == nil {
                
            }
        }
    }
    private func _beInquireIntoLocationsAddress(location: CLLocation) {
        var action = FoundLocationsAddressAction()
        GeoCoder().beReverseLocation(self, location: location) { (placemarks, error) in
            if placemarks?.count ?? 0 > 0 {
                DataManager().beParsePlaceMarktoGQInput(self, placemarks!) {
                    (inputObjs) in
                    action.inputObjects = inputObjs
                    appStore.dispatch(action)
                }
            }
        }
    }
    
    // MARK: - Pilot protocols
    private func _beLocationManager(didUpdateLocations locations: [CLLocation]) {
        if locations.count > 0 {
            beInquireIntoLocationsAddress(location: locations[0])
        }
    }
    
    private func _beLocationManager(didFailWithError error: Error) {
    }
    
    private func _beLocationManager(didChangeAuthorization status: CLAuthorizationStatus) {
    }
    
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension SearchLocScenario {

    @discardableResult
    public func beRequestCurrentLocation() -> Self {
        unsafeSend(_beRequestCurrentLocation)
        return self
    }
    @discardableResult
    public func beInquireIntoAddressesLocation(address: String) -> Self {
        unsafeSend { self._beInquireIntoAddressesLocation(address: address) }
        return self
    }
    @discardableResult
    public func beInquireIntoLocationsAddress(location: CLLocation) -> Self {
        unsafeSend { self._beInquireIntoLocationsAddress(location: location) }
        return self
    }
    @discardableResult
    public func beLocationManager(didUpdateLocations locations: [CLLocation]) -> Self {
        unsafeSend { self._beLocationManager(didUpdateLocations: locations) }
        return self
    }
    @discardableResult
    public func beLocationManager(didFailWithError error: Error) -> Self {
        unsafeSend { self._beLocationManager(didFailWithError: error) }
        return self
    }
    @discardableResult
    public func beLocationManager(didChangeAuthorization status: CLAuthorizationStatus) -> Self {
        unsafeSend { self._beLocationManager(didChangeAuthorization: status) }
        return self
    }

}
