//
//  AddGourmetScenario.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/14.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn

struct DropDownMenuData
{
    let typeSource = ["Unclassified",
                      "Breakfast","Boxed meal",
                      "Buffet","Cafe","Cafeteria","Diner","Fast food",
                      "Prix fixe","Pizzeria"]
    let styleSource = ["Unclassified","AFR","EURO","LAME",
                       "CHN","DEU","ESP","GBR","FRA","HKG",
                       "IND","JPN","KOR","MEX","THA",
                       "TWN","USA","VNM"]
}
struct GourmetsTableData {
    var inputObj: GQInputObject
    var dataSource: Array<Array<TemplateProtocol>> = []
    init(address: GQInputObject) {
        self.inputObj = address
        dataSource = createDataSource()
    }
    let sectionTitles : Array<String> = ["Shop","Branch","Location"]
    private func createDataSource() -> Array<Array<TemplateProtocol>> {
        return [
            [
                LRTemplate(leftViewItem: LabelItem(text: "Title"),
                               rightViewItem: TextFieldItem(text: self.inputObj.shop.title)),
                LRTemplate(leftViewItem: DropDownItem(placeHolder:"Style", optionArray: DropDownMenuData().styleSource,
                                                                selectedText: (self.inputObj.shop.style ?? "") ?? ""),
                               rightViewItem: DropDownItem(placeHolder:"Type",
                                                                 optionArray: DropDownMenuData().typeSource,
                                                                 selectedText: (self.inputObj.shop.type ?? "") ?? "")),
                LRTemplate(leftViewItem: LabelItem(text: "Under\nPrice"),
                               rightViewItem: TextFieldItem(keyboardType: .decimalPad,
                                                                  text: String(format: "%.2f", self.inputObj.shop.underPrice)))
            ],
            [
                LRTemplate(leftViewItem: LabelItem(text: "Name"), rightViewItem: TextFieldItem(text: self.inputObj.shopBranch.name)),
                LRTemplate(leftViewItem: LabelItem(text: "Tel"),
                               rightViewItem: TextFieldItem(keyboardType: .phonePad, text: (inputObj.shopBranch.tel ?? "") ?? ""))
            ],
            [
                LRTemplate(leftViewItem: LabelItem(text: "Address"),
                               rightViewItem: LabelItem(numberOfLines: 2, text: inputObj.address.completeInfo),
                           itemHeight: 84.0
                ),
                LRTemplate(
                    leftViewItem: LabelItem(text: "Floor"),
                    rightViewItem: TextFieldItem(keyboardType: .numberPad,
                        text: (self.inputObj.address.floor ?? "") ?? "")),
                LRTemplate(leftViewItem: LabelItem(text: "Room"), rightViewItem: TextFieldItem(keyboardType: .numberPad,text: (self.inputObj.address.room ?? "") ?? "")),
                ButtonTemplate(cornerRadius: 2.0, titleText: "Save")
            ]
        ]
    }
}

// MARK: - AddGourmetScenario
class AddGourmetScenario: Actor {
    
    private var queryData = initGQInputObject()
    
    private func _beCollectGQInputPacel() {
        LogisticsCenter.shared.collectParcels(recipient: self) { [self] (parcelSet) in
            guard parcelSet?.count ?? 0 > 0 else {return}
            for parcel in parcelSet! {
                let parcelItem = parcel as! Parcel
                if let content = parcelItem.content as? GQInputObject {
                    queryData = content
                }
            }
        }
    }
    private func _beGetInputData(
        _ complete: @escaping (GQInputObject) -> Void) {
        complete(queryData)
    }
    private func _beUpdateInputData(newInput: GQInputObject) {
        queryData = newInput
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension AddGourmetScenario {

    @discardableResult
    public func beCollectGQInputPacel() -> Self {
        unsafeSend(_beCollectGQInputPacel)
        return self
    }
    @discardableResult
    public func beGetInputData(_ complete: @escaping (GQInputObject) -> Void) -> Self {
        unsafeSend { self._beGetInputData(complete) }
        return self
    }
    @discardableResult
    public func beUpdateInputData(newInput: GQInputObject) -> Self {
        unsafeSend { self._beUpdateInputData(newInput: newInput) }
        return self
    }

}
