//
//  FoundLocScenario.swift
//  WhatToEat
//
//  Created by YuCheng on 2021/2/20.
//  Copyright © 2021 YuCheng. All rights reserved.
//

import Foundation
import Flynn
import ReSwift

class FoundLocScenario: Actor {
    
    private func _beCollectParcel(
        _ complete: @escaping (
            [GQInputObject]) -> Void) {
        Courier().beClaim(recipient: self) { parcelSet in
            guard parcelSet.count > 0 else {return}
            for parcel in parcelSet {
                if let parcelItem = parcel as? Parcel<[GQInputObject]> {
                    complete(parcelItem.content)
                }
            }
        }
    }
    private func _bePrepareNewParcel(inputObj: GQInputObject) {
        var newData = initGQInputObject()
        newData.address = inputObj.address
        bePackageParcel(inputObj: newData)
    }
    private func _bePackageParcel(inputObj: GQInputObject) {
        Courier().beApplyExpress(
            sender: self, recipient: String(describing: AddGourmetScenario.self),
            content: inputObj, nil)
    }
}

// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension FoundLocScenario {

    @discardableResult
    public func beCollectParcel(_ complete: @escaping (
            [GQInputObject]) -> Void) -> Self {
        unsafeSend { self._beCollectParcel(complete) }
        return self
    }
    @discardableResult
    public func bePrepareNewParcel(inputObj: GQInputObject) -> Self {
        unsafeSend { self._bePrepareNewParcel(inputObj: inputObj) }
        return self
    }
    @discardableResult
    public func bePackageParcel(inputObj: GQInputObject) -> Self {
        unsafeSend { self._bePackageParcel(inputObj: inputObj) }
        return self
    }

}
